package UI;

import Products.IProduct;
import Products.MediumType;
import Products.ProductSystem;
import Products.ProductType;
import Users.User;
import Users.UserSystem;
import Utils.UiUtils;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class StoreScreen extends javax.swing.JFrame {

    private Map<Integer, Integer> tableIndexToProductIdMap = new HashMap<>();

    public StoreScreen() {
        initComponents();

        // product type combobox fill
        productType.setModel(new DefaultComboBoxModel(ProductType.values()));
    }

    private void fillTheTable(MediumType medium, ProductType type) {
        //itemTable.removeAll();

        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.setRowCount(0);

        ArrayList<IProduct> allProducts = ProductSystem.getAllProducts(medium, type);

        DefaultTableModel dtm = (DefaultTableModel) itemTable.getModel();

        for (int i = 0; i < allProducts.size(); i++) {
            IProduct it = allProducts.get(i);
            tableIndexToProductIdMap.put(i, it.getProductId());
            dtm.addRow(UiUtils.convertProductToRowItem(it));
        }
    }

    private void refreshTableWithFilters() {
        fillTheTable(getSelectedMediumType(), getSelectedProductType());
    }

    private MediumType getSelectedMediumType() {
        MediumType medium = MediumType.Physical;
        if (digitalMedium.isSelected()) {
            medium = MediumType.Digital;
        }

        return medium;
    }

    private ProductType getSelectedProductType() {
        return (ProductType) productType.getSelectedItem();
    }

    private IProduct getSelectedProduct() {
        int selectedIndex = itemTable.getSelectedRow();

        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Nothing is selected.");
            return null;
        }

        Integer selectedId = tableIndexToProductIdMap.get(selectedIndex);

        if (selectedId == null) {
            JOptionPane.showMessageDialog(null, "Cannot find the product associated with the selected row.");
            return null;
        }

        IProduct selectedProduct = ProductSystem.searchProduct(selectedId);

        if (selectedProduct == null) {
            JOptionPane.showMessageDialog(null, "Product is null.");
            return null;
        }

        return selectedProduct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        productType = new javax.swing.JComboBox<>();
        buyButton = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        digitalMedium = new javax.swing.JRadioButton();
        phsyicalMedium = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        usernameOutput = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        removeProductButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        productType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTypeActionPerformed(evt);
            }
        });

        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        searchInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        searchButton.setText("🔎 Search");

        jLabel1.setText("Product Type");

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", null},
                {null, null, "", null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Genre", "Language", "Publisher", "Release Date", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        jLabel2.setText("Medium");

        buttonGroup1.add(digitalMedium);
        digitalMedium.setSelected(true);
        digitalMedium.setText("Digital");
        digitalMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitalMediumActionPerformed(evt);
            }
        });

        buttonGroup1.add(phsyicalMedium);
        phsyicalMedium.setText("Physical");
        phsyicalMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phsyicalMediumActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Welcome");

        usernameOutput.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        usernameOutput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameOutput.setText("LONGLONG NAMENAME");

        addProductButton.setText("Add a new Product...");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        inventoryButton.setText("Switch to Inventory View");
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        removeProductButton.setText("Remove Product");
        removeProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Double click a product for detailed information.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeProductButton)
                        .addGap(18, 18, 18)
                        .addComponent(addProductButton)
                        .addGap(18, 18, 18)
                        .addComponent(buyButton)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(digitalMedium)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phsyicalMedium)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(productType, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usernameOutput)))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addProductButton, buyButton, removeProductButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(digitalMedium)
                    .addComponent(phsyicalMedium)
                    .addComponent(jLabel3)
                    .addComponent(usernameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buyButton)
                        .addComponent(addProductButton)
                        .addComponent(inventoryButton)
                        .addComponent(removeProductButton)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        IProduct product = getSelectedProduct();

        if (product != null) {
            if (evt.getClickCount() == 2) {
                WindowManager.ProductInfo.setUpForViewOrEdit(product, UserSystem.getLoggedInUser().isAdmin());
                WindowManager.ProductInfo.setVisible(true);
            }
        }
    }//GEN-LAST:event_itemTableMouseClicked

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        WindowManager.Inventory.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        WindowManager.ProductInfo.setUpForAdd(getSelectedMediumType(), getSelectedProductType());
        WindowManager.ProductInfo.setVisible(true);
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        addProductButton.setVisible(UserSystem.getLoggedInUser().isAdmin());
        removeProductButton.setVisible(UserSystem.getLoggedInUser().isAdmin());

        usernameOutput.setText(UserSystem.getLoggedInUser().getName().toUpperCase() + " " + UserSystem.getLoggedInUser().getSurname().toUpperCase());

        refreshTableWithFilters();
    }//GEN-LAST:event_formWindowActivated

    private void productTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTypeActionPerformed
        refreshTableWithFilters();
    }//GEN-LAST:event_productTypeActionPerformed

    private void phsyicalMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phsyicalMediumActionPerformed
        refreshTableWithFilters();
    }//GEN-LAST:event_phsyicalMediumActionPerformed

    private void digitalMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitalMediumActionPerformed
        refreshTableWithFilters();
    }//GEN-LAST:event_digitalMediumActionPerformed

    private void removeProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductButtonActionPerformed
        try {
            IProduct selected = getSelectedProduct();
            ProductSystem.deleteProduct(selected.getProductId());
            this.refreshTableWithFilters();
            ProductSystem.saveAllToFile();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "File error during removal:\n" + ex.toString());
        }
    }//GEN-LAST:event_removeProductButtonActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        IProduct selected = getSelectedProduct();

        User u = UserSystem.getLoggedInUser();

        if (selected == null) {
            return;
        }

        try {
            u.registerPurchasedProduct(selected);
            JOptionPane.showMessageDialog(null, "Product added.");
            UserSystem.writeAllToFile();
            JOptionPane.showMessageDialog(null, "Purchase successful.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "File error during purchase:\n" + ex.toString());
        }
    }//GEN-LAST:event_buyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buyButton;
    private javax.swing.JRadioButton digitalMedium;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton phsyicalMedium;
    private javax.swing.JComboBox<String> productType;
    private javax.swing.JButton removeProductButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JLabel usernameOutput;
    // End of variables declaration//GEN-END:variables
}
